---
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres_data:
